import DifferentialInvariantsLocalTheoryGeometricLemmaCanonicalLaneLean.RecurrenceFormula

/-!
# Geometric Lemma Local Theory Package

This module formalizes the Geometric Lemma: that all differential invariants are generated by a finite set under differentiation.
-/

namespace HautevilleHouse
namespace DifferentialInvariantsLocalTheoryGeometricLemmaCanonicalLaneLean

structure FormalPowerSeriesAlgebra (M : Type u) where
  baseRing : Type v
  generators : ℕ → Type w
  finitelyGenerated : Prop
  closureUnderDerivation : Prop
  syzygyModuleFinitelyGenerated : Prop

structure GeometricLemma (M : Type u) (A : LieGroupAction M) (F : MovingFrame M A) where
  generatingInvariants : DifferentialInvariantBundle M (default : JetBundle M)
  recurrenceOperator : RecurrenceOperator M A F
  allInvariantsGenerated : Prop
  noetherianProperty : Prop
  differentialAlgebra : FormalPowerSeriesAlgebra M
  syzygies : SyzygyBundle M A
  syzygiesResolved : Prop

structure GeometricLemmaEvidence (M : Type u) (A : LieGroupAction M) (F : MovingFrame M A)
    (G : GeometricLemma M A F) where
  allInvariantsGeneratedClosed : G.allInvariantsGenerated
  noetherianPropertyClosed : G.noetherianProperty
  syzygiesResolvedClosed : G.syzygiesResolved
  differentialAlgebraFinitelyGenerated : G.differentialAlgebra.finitelyGenerated
  closureUnderDerivationClosed : G.differentialAlgebra.closureUnderDerivation

def GeometricLemmaClosed (M : Type u) (A : LieGroupAction M) (F : MovingFrame M A)
    (G : GeometricLemma M A F) : Prop :=
  G.allInvariantsGenerated ∧ G.noetherianProperty ∧ G.syzygiesResolved ∧
  G.differentialAlgebra.finitelyGenerated ∧ G.differentialAlgebra.closureUnderDerivation

theorem geometric_lemma_closed_from_evidence
    (M : Type u) (A : LieGroupAction M) (F : MovingFrame M A)
    (G : GeometricLemma M A F) (E : GeometricLemmaEvidence M A F G) :
    GeometricLemmaClosed M A F G := by
  exact And.intro E.allInvariantsGeneratedClosed
    (And.intro E.noetherianPropertyClosed
      (And.intro E.syzygiesResolvedClosed
        (And.intro E.differentialAlgebraFinitelyGenerated
          E.closureUnderDerivationClosed)))

end DifferentialInvariantsLocalTheoryGeometricLemmaCanonicalLaneLean
end HautevilleHouse